<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <OutDir>$(SolutionDir)bin\$(Configuration)\</OutDir>
    <IntDir>$(SolutionDir)Intermediate\$(ProjectName)\$(Configuration)\</IntDir>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(SolutionDir)externals\glfw\include;$(SolutionDir)externals\glew\include;$(SolutionDir)externals\glm;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <ScanSourceForModuleDependencies>true</ScanSourceForModuleDependencies>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>$(SolutionDir)externals\glfw\lib-vc2026;$(SolutionDir)externals\glew\lib\Release\$(Platform);%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
      <AdditionalDependencies>opengl32.lib;glew32.lib;glfw3dll.lib;%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
    <PostBuildEvent>
      <Command>xcopy /y /d "$(SolutionDir)externals\glew\bin\Release\$(Platform)\glew32.dll" "$(OutDir)"
xcopy /y /d "$(SolutionDir)externals\glfw\lib-vc2026\glfw3.dll" "$(OutDir)"</Command>
    </PostBuildEvent>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>